import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { anekTamil } from "./fonts";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "page title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${anekTamil.variable}`}>
        {children}
      </body>
    </html>
  );
}
