import Image from "next/image";
import { anekTamil } from "./fonts";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  openGraph:{
    title: "Home Page",
    description: "Generated by create next app",
    url: "https://www.example.com/home",
  }
};

export default function Home() {
  return (
    <h3 className={anekTamil.className}>Hello World</h3>
  );
}
